use_amp: True
use_ema: True 
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

epoches: 72
clip_max_norm: 0.1

optimizer:
  type: SGD
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.001        
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.01             
  momentum: 0.937      
  weight_decay: 0.0005
  nesterov: True       

lr_scheduler:
  type: MultiStepLR
  milestones: [1000]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 3000  